config/routes.rb
Rails.application.routes.draw do

   root 'pages#index'

   get '/auth/:provider/callback', to: 'sessions#create'

   get '/profile' => 'pages#profile', as: :profile
   resources :habits, only: [:create]
   resources :sponsorships, only: [:create]

   get '/login' => 'sessions#new', as: :login
   get '/logout' => 'sessions#destroy', as: :logout
   get '/auth/failure' => 'sessions#failure'

end

app/models/habit.rb
class Habit < ActiveRecord::Base
  has_many :sponsorship
  belongs_to :user

  validates :title, presence: true
  validates :days, presence: true
end

app/models/sponsorship.rb
class Sponsorship < ActiveRecord::Base

  belongs_to :habit
  belongs_to :user

  validates :habit_id, presence: true
  validates :amount, presence: true
  validates :interval, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :habits
  has_many :sponsorships

  def self.find_or_create_by_uid(provider, uid, token)
    if user = User.find_by_uid(uid)
      return user
    else
      user = User.create(provider: provider, uid: uid, access_token: token)
      return user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue Exception => e
      nil
    end
  end

  def user_signed_in?
    return true if current_user
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, alert: "Access denied"
    end
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, alert: "Please sign in first."
    end
  end

end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @habit = current_user.habits.create(habit_params)
    respond_to do |format|
      format.html
      format.js
    end
  end

private
def habit_params
  params.require(:habit).permit(:title, :days)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
    @habits = Habit.all.order('created_at DESC')
    @sponsorship = Sponsorship.new
  end

  def profile
    @habit = Habit.new
    @user = current_user
    @habits = current_user.habits.order('created_at DESC')
    @sponsorships = current_user.sponsorships.order('created_at DESC')
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to "https://api.venmo.com/v1/oauth/authorize?client_id=#{ENV['VENMO_CLIENT_ID']}&scope=access_profile&response_type=code&redirect_uri=#{request.protocol + request.host_with_port}/auth/venmo/callback"
  end

  def create
    post_params = { 'client_id' => ENV['VENMO_CLIENT_ID'], 'code' => params['code'], 'client_secret' => ENV['VENMO_CLIENT_SECRET'] }
    puts params

    uri = URI.parse("https://api.venmo.com/v1/oauth/access_token")
    uri.query = URI.encode_www_form(post_params)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    req = Net::HTTP::Post.new(uri.request_uri)
    token = JSON.load(http.request(req).body)

    user = User.find_or_create_by_uid(params['provider'], token['user']['id'].to_s, token['access_token'].to_s)

    reset_session
    session[:user_id] = user.id
    redirect_to root_url, notice: "Logged in."
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Logged out."
  end

  def failure
    redirect_to root_url, alert: "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/sponsorships_controller.rb
class SponsorshipsController < ApplicationController

  def create
    @sponsorship = current_user.sponsorships.create(sponsorship_params)
    redirect_to profile_path
  end

private
def sponsorship_params
  params.require(:sponsorship).permit(:habit_id, :amount, :interval)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sponsorships_helper.rb
module SponsorshipsHelper
end

app/views/habits/_habit.html.haml
%li.habit-item
  %span.habit-status
    - if habit.status
      %i{class: 'fa fa-check-square-o'}
    - else
      %i{class: 'fa fa-square-o'}
  %span.date.habit-data
    = "#{habit.created_at.strftime("%m-%e-%Y")} -"
  %span.title.habit-data
    = habit.title
  for
  %span.days.habit-data
    = habit.days
  days
  - if habit.user_id != current_user.id
    = render partial: "sponsorships/new", locals: { habit_id: habit.id }

app/views/habits/_new.html.haml
.create-habit
  = simple_form_for @habit, remote: true do |f|
    %h4
      What would you like to do?
    = f.input :title, label: false, placeholder: "Title"
    %h4
      For how many days?
    = f.input :days, label: false, placeholder: "Days"
    = f.button :submit, class: 'btn btn-default'

app/views/habits/create.js.erb
$('<%= escape_javascript(render partial: 'habits/habit', locals: { habit: @habit }) %>').prependTo('#habits-list').hide().fadeIn('slow');
$('#habit_title').val("");
$('#habit_days').val("");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Habithacks
    %link{href: '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css', type: 'text/css', rel: 'stylesheet'}
    %link{href: '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', type: 'text/css', rel: 'stylesheet'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{src: 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js'}
    %script{src: '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js'}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if user_signed_in?
      .navbar-default
        .container
          = link_to "Habit Hacks", root_path, class: 'navbar-brand main-title'
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to "Home", root_path
            %li
              = link_to "Profile", profile_path
            %li
              = link_to "Logout", logout_path
    .container.text-center
      .row
        .col-sm-10.col-sm-offset-1
          = yield

app/views/pages/index.html.haml
- if user_signed_in?
  %section.user-container
    %h1 Sponsor a Habit
    %ul.list-unstyled.habits-list#habits-list
      - @habits.each do |habit|
        = render partial: 'habits/habit', locals: { habit: habit }
    %br
- else
  %section.visitor-container
    = link_to "LOGIN", login_path, class: 'btn btn-large'

app/views/pages/profile.html.haml
= render partial: 'habits/new'
%h1 Your Habits
%ul.list-unstyled.habits-list#habits-list
  - @habits.each do |habit|
    = render partial: 'habits/habit', locals: { habit: habit }
%br

%h1 Sponsorships
%ul.list-unstyled.sponsorships-list#sponsorships-list
  - @sponsorships.each do |sponsorship|
    = render partial: 'sponsorships/sponsorship', locals: { sponsorship: sponsorship }
%br

app/views/sponsorships/_new.html.haml
.sponsor-habit-form
  = simple_form_for @sponsorship do |f|
    = f.hidden_field :habit_id, value: habit_id
    = f.input :amount, label: false, placeholder: "$ Amount", id: "amount"
    = f.input :interval, label: false, placeholder: "Interval (days)", id: "interval"
    = f.button :submit, "Sponsor", class: 'btn btn-default'

app/views/sponsorships/_sponsorship.html.haml
-#= "You sponsored #{sponsorship.sponsorship.title} for #{sponsorship.sponsorship.days} days | $#{sponsorship.amount/sponsorship.interval} every #{sponsorship.interval} days."
%li.sponsorship-item
  You sponsored
  %span.title.sponsorship-data
    = sponsorship.habit.title
  for
  %span.days.sponsorship-data
    = sponsorship.habit.days
  days ||
  %span.amount.sponsorship-data
    = "$#{sponsorship.amount/sponsorship.interval}"
  every
  %span.interval.sponsorship-data
    = sponsorship.interval
  days
  - if sponsorship.user_id != current_user.id
    = render partial: "sponsorships/new", locals: { sponsorship: sponsorship.id }